In [194]:
#importing the libraries
import pandas as pd
import numpy as np
import datetime as dt

***Flipkart_dataset-Data Wrangling***

In [195]:
#creating dataframe
df_flipkart=pd.read_csv('flipkart_women_shirts_full.csv')
print("Total number of rows in flipkart_women_shirts_full.csv: ", len(df_flipkart))

Total number of rows in flipkart_women_shirts_full.csv:  362

In [196]:
df_flipkart.head(2)

,website_name,product_name,product_image,brand,category,subcategory,price,original_price,discount_percent,rating,...,color,fit_type,fabric,sleeve_type,pattern,description,availability,seller,product_url,scrape_date
0,Flipkart,FUNDAY FASHION Women Solid Casual Black Shirt,https://rukmini1.flixcart.com/image/1500/1500/...,FUNDAY FASHION,Women Fashion,Shirts,350,1499,76,3.8,...,Black,Regular Fit,Viscose Rayon,NaN,Solid,FUNDAY FASHION Women Solid Casual Black Shirt ...,In Stock,SYSONLINESTORE,https://www.flipkart.com/funday-fashion-women-...,2026-06-29T09:51:50.428664+00:00
1,Flipkart,FUNDAY FASHION Women Solid Casual Maroon Shirt,https://rukmini1.flixcart.com/image/1500/1500/...,FUNDAY FASHION,Women Fashion,Shirts,344,1499,77,3.8,...,WIne,Regular Fit,Viscose Rayon,NaN,Solid,FUNDAY FASHION Women Solid Casual Maroon Shirt...,In Stock,SYSONLINESTORE,https://www.flipkart.com/funday-fashion-women-...,2026-06-29T09:51:50.428664+00:00

In [197]:
df_flipkart.shape

(362, 22)

In [198]:
df_flipkart.isnull().sum()

website_name          0
product_name          0
product_image         0
brand                 0
category              0
subcategory           0
price                 0
original_price        0
discount_percent      0
rating               53
review_count         53
size_options          1
color                 0
fit_type              5
fabric                4
sleeve_type         362
pattern               0
description           1
availability          1
seller                1
product_url           0
scrape_date           0
dtype: int64

In [199]:
df_flipkart["availability"]=df_flipkart["availability"].fillna("unknown")

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\3507374872.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_flipkart["availability"]=df_flipkart["availability"].fillna("unknown")

In [200]:
df_flipkart["seller"]=df_flipkart["seller"].fillna("unknown")

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\2782801636.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_flipkart["seller"]=df_flipkart["seller"].fillna("unknown")

In [201]:
df_flipkart["description"]=df_flipkart["description"].fillna("unknown")

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\1714886325.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_flipkart["description"]=df_flipkart["description"].fillna("unknown")

In [202]:
df_flipkart["size_options"]=df_flipkart["size_options"].fillna("unknown")

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\2281469660.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_flipkart["size_options"]=df_flipkart["size_options"].fillna("unknown")

In [203]:
df_flipkart["rating"]=df_flipkart["rating"].fillna("0")

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\1869346729.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_flipkart["rating"]=df_flipkart["rating"].fillna("0")

In [204]:
df_flipkart["review_count"]=df_flipkart["review_count"].fillna("0")

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\3485146741.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_flipkart["review_count"]=df_flipkart["review_count"].fillna("0")

In [205]:
df_flipkart["fit_type"]=df_flipkart["fit_type"].fillna("unknown")

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\4286071840.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_flipkart["fit_type"]=df_flipkart["fit_type"].fillna("unknown")

In [206]:

df_flipkart["sleeve_type"]=df_flipkart["sleeve_type"].fillna("unknown")

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\291342247.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_flipkart["sleeve_type"]=df_flipkart["sleeve_type"].fillna("unknown")

In [207]:
df_flipkart["fabric"]=df_flipkart["fabric"].fillna("unknown")

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\3685853121.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_flipkart["fabric"]=df_flipkart["fabric"].fillna("unknown")

***Amazon_dataset-Data Wrangling***

In [208]:
#creating dataframes
df_amazon=pd.read_csv('amazon_women_shirts_full.csv')
print("Total number of rows in amazon_women_shirts_full.csv: ", len(df_amazon))

Total number of rows in amazon_women_shirts_full.csv:  423

In [209]:
df_amazon.shape

(423, 22)

In [210]:
df_amazon.head(2)

,website_name,product_name,product_image,brand,category,subcategory,price,original_price,discount_percent,rating,...,color,fit_type,fabric,sleeve_type,pattern,description,availability,seller,product_url,scrape_date
0,Amazon India,Van Heusen Women Polyester Regular Fit Solid F...,https://m.media-amazon.com/images/I/51mWd7jXVP...,Van Heusen,Clothing & Accessories,Button-Down Shirts,1985.0,2299.0,13.66,3.9,...,Beige,Regular Fit,Polyester,Long Sleeve,Solid,This Top from Van Heusen Women is a perfect ad...,In stock,Cocoblu Retail,https://www.amazon.in/dp/B0GT5NXT1S,2026-06-26T08:41:34.085456+00:00
1,Amazon India,Van Heusen Women Polyester Regular Fit Solid H...,https://m.media-amazon.com/images/I/610tXYDRIe...,Van Heusen,Clothing & Accessories,Button-Down Shirts,1586.0,2299.0,31.01,4.1,...,Beige,Regular Fit,Polyester,Half Sleeve,Solid,This Top from Van Heusen Women is a perfect ad...,In stock,Cocoblu Retail,https://www.amazon.in/dp/B0G6FK24Z4,2026-06-26T08:41:34.085456+00:00

In [211]:
df_amazon.isnull().sum()

website_name          0
product_name          0
product_image         1
brand                 0
category              0
subcategory           0
price                 2
original_price        8
discount_percent      8
rating               15
review_count         29
size_options        187
color               104
fit_type            129
fabric              120
sleeve_type         103
pattern             105
description          18
availability          0
seller              325
product_url           0
scrape_date           0
dtype: int64

In [212]:
#Price-related repairs
df_amazon["original_price"] = df_amazon["original_price"].fillna(df_amazon["price"])
df_amazon["discount_percent"] = pd.to_numeric(df_amazon["discount_percent"], errors="coerce")
mask = df_amazon["discount_percent"].isna() & df_amazon["original_price"].gt(0)
df_amazon.loc[mask, "discount_percent"] = (
    (df_amazon["original_price"] - df_amazon["price"]) / df_amazon["original_price"] * 100
).round(2)
df_amazon["discount_percent"] = df_amazon["discount_percent"].fillna(0)

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\1435999462.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_amazon["original_price"] = df_amazon["original_price"].fillna(df_amazon["price"])
C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\1435999462.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_amazon["discount_percent"] = pd.to_numeric(df_amazon["discount_percent"], errors="coerce")
C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\1435999462.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_amazon["discount_percent"] = df_amazon["discount_percent"].fillna(0)

In [213]:
# Engagement metrics
df_amazon["rating"] = df_amazon["rating"].fillna(0)
df_amazon["review_count"] = df_amazon["review_count"].fillna(0)

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\2293580253.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_amazon["rating"] = df_amazon["rating"].fillna(0)
C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\2293580253.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_amazon["review_count"] = df_amazon["review_count"].fillna(0)

In [214]:
#  Categorical / text
for col in ["seller", "size_options", "fit_type", "fabric", "pattern",
            "color", "sleeve_type", "description", "product_image"]:
    df_amazon[col] = df_amazon[col].fillna("unknown")

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\4092696779.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_amazon[col] = df_amazon[col].fillna("unknown")

***Myntra_Dataset- Data Wrangling***

In [215]:
#creating dataframes
df_myntra=pd.read_csv('myntra_women_shirts_full.csv')
print("Total number of rows in myntra_women_shirts_full.csv: ", len(df_myntra))

Total number of rows in myntra_women_shirts_full.csv:  468

In [216]:
df_myntra.head(2)

,website_name,product_name,product_image,brand,category,subcategory,price,original_price,discount_percent,rating,...,color,fit_type,fabric,sleeve_type,pattern,description,availability,seller,product_url,scrape_date
0,Myntra,Style Quotient Women White Formal Shirt,"https://assets.myntassets.com/h_720,q_70,w_540...",Style Quotient,Apparel,Shirts,599,1499,60,4.3,...,White,Regular Fit,Cotton,Long Sleeves,Solid,"White solid opaque foraml shirt ,has a spread ...",InStock,Savadika Retail Private Limited,https://www.myntra.com/Shirts/Style+Quotient/S...,2026-06-26T05:32:19.624356+00:00
1,Myntra,glitchez Women Striped Casual Shirt,"https://assets.myntassets.com/h_720,q_70,w_540...",glitchez,Apparel,Shirts,596,1999,70,2.9,...,White,Regular Fit,Polyester,Long Sleeves,Striped,"White Solid Striped Opaque Casual shirts ,has ...",InStock,AAHWAN ENTERPRISE,https://www.myntra.com/Shirts/glitchez/glitche...,2026-06-26T05:32:19.624356+00:00

In [217]:
df_myntra.shape

(468, 22)

In [218]:
df_myntra.isnull().sum()

website_name        0
product_name        0
product_image       0
brand               0
category            0
subcategory         0
price               0
original_price      0
discount_percent    6
rating              0
review_count        0
size_options        0
color               0
fit_type            0
fabric              6
sleeve_type         0
pattern             0
description         0
availability        0
seller              0
product_url         0
scrape_date         0
dtype: int64

In [219]:
# If discount_percent is null, calculate it from price and original_price
df_myntra['price'] = pd.to_numeric(df_myntra['price'], errors='coerce')
df_myntra['original_price'] = pd.to_numeric(df_myntra['original_price'], errors='coerce')
df_myntra['discount_percent'] = pd.to_numeric(df_myntra['discount_percent'], errors='coerce')

calculated_discount = (
    (df_myntra['original_price'] - df_myntra['price'])
    / df_myntra['original_price']
) * 100

# Only fill rows where discount_percent is null
df_myntra['discount_percent'] = df_myntra['discount_percent'].fillna(calculated_discount)
df_myntra['discount_percent'] = df_myntra['discount_percent'].round().astype('Int64')

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\235898018.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_myntra['price'] = pd.to_numeric(df_myntra['price'], errors='coerce')
C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\235898018.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_myntra['original_price'] = pd.to_numeric(df_myntra['original_price'], errors='coerce')
C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\235898018.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_myntra['discount_percent'] = pd.to_numeric(df_myntra['discount_percent'], errors='coerce')
C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\235898018.py:12: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_myntra['discount_percent'] = df_myntra['discount_percent'].fillna(calculated_discount)
C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\235898018.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_myntra['discount_percent'] = df_myntra['discount_percent'].round().astype('Int64')

In [220]:
#replacing the / with ,
df_myntra['size_options'].replace('/',',',inplace=True)
df_myntra['size_options']=df_myntra['size_options'].str.split(',')
df_myntra['size_options']=df_myntra['size_options'].fillna("unknown")

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\2112617665.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_myntra['size_options'].replace('/',',',inplace=True)
C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\2112617665.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_myntra['size_options']=df_myntra['size_options'].str.split(',')
C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\2112617665.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_myntra['size_options']=df_myntra['size_options'].fillna("unknown")

In [221]:
import ast

def to_csv_string(x):
    if isinstance(x, list):
        return ','.join(x)
    if isinstance(x, str) and x.startswith('['):
        return ','.join(ast.literal_eval(x))   # "['S', 'M']" -> "S,M"
    return x

df_myntra['size_options'] = df_myntra['size_options'].apply(to_csv_string)

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\2861026618.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_myntra['size_options'] = df_myntra['size_options'].apply(to_csv_string)

In [222]:
#transforming the column names in lower case
df_myntra.columns=df_myntra.columns.str.lower()

In [223]:
#checking the datatypes
df_myntra.dtypes

website_name         object
product_name         object
product_image        object
brand                object
category             object
subcategory          object
price                 int64
original_price        int64
discount_percent      Int64
rating              float64
review_count          int64
size_options         object
color                object
fit_type             object
fabric               object
sleeve_type          object
pattern              object
description          object
availability         object
seller               object
product_url          object
scrape_date          object
dtype: object

***Ajio_Dataset-Data Wrangling***

In [224]:
#creating dataframes
df_ajio=pd.read_csv('ajio_women_shirts_full.csv')
print("Total number of rows in ajio_women_shirts_full.csv: ", len(df_ajio))

Total number of rows in ajio_women_shirts_full.csv:  980

In [225]:
df_ajio.head(2)

,website_name,product_name,product_image,brand,category,subcategory,price,original_price,discount_percent,rating,...,color,fit_type,fabric,sleeve_type,pattern,description,availability,seller,product_url,scrape_date
0,Ajio,Bollyclues Coffee Women Embroidered Regular Fi...,https://assets.ajio.com/medias/sys_master/root...,Bollyclues,Women,Shirts,343,999,51.0,NaN,...,Brown,Regular Fit,NaN,NaN,Embroidered,Bollyclues Coffee Women Embroidered Regular Fi...,InStock,NaN,https://www.ajio.com/bollyclues-women-embroide...,2026-06-26T12:13:00.063541+00:00
1,Ajio,Nyrika Off White Women Embroidery Relaxed Fit ...,https://assets.ajio.com/medias/sys_master/root...,Nyrika,Women,Shirts,500,2499,77.0,NaN,...,Off White,Relaxed Fit,NaN,NaN,NaN,Nyrika Off White Women Embroidery Relaxed Fit ...,InStock,NaN,https://www.ajio.com/nyrika-women-embroidery-r...,2026-06-26T12:13:00.063541+00:00

In [226]:
df_ajio.shape

(980, 22)

In [227]:
df_ajio.isnull().sum()

website_name          0
product_name          0
product_image         0
brand                 0
category              0
subcategory           0
price                 0
original_price        0
discount_percent     13
rating              980
review_count        980
size_options        614
color                 0
fit_type            123
fabric              925
sleeve_type         966
pattern             493
description           0
availability          0
seller              980
product_url           0
scrape_date           0
dtype: int64

In [228]:
#Price-related repairs
df_ajio["original_price"] = df_ajio["original_price"].fillna(df_ajio["price"])
df_ajio["discount_percent"] = pd.to_numeric(df_ajio["discount_percent"], errors="coerce")
mask = df_ajio["discount_percent"].isna() & df_ajio["original_price"].gt(0)
df_ajio.loc[mask, "discount_percent"] = (
    (df_ajio["original_price"] - df_ajio["price"]) / df_ajio["original_price"] * 100
).round(2)

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\73457725.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_ajio["original_price"] = df_ajio["original_price"].fillna(df_ajio["price"])
C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\73457725.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_ajio["discount_percent"] = pd.to_numeric(df_ajio["discount_percent"], errors="coerce")

In [229]:
#Engagement metrics
df_ajio["rating"] = df_ajio["rating"].fillna(0)
df_ajio["review_count"] = df_ajio["review_count"].fillna(0)
#  Categorical / text
for col in ["seller", "size_options", "fit_type", "fabric", "pattern",
            "color", "sleeve_type", "description", "product_image"]:
    df_ajio[col] = df_ajio[col].fillna("unknown")

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\1690823416.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_ajio["rating"] = df_ajio["rating"].fillna(0)
C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\1690823416.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_ajio["review_count"] = df_ajio["review_count"].fillna(0)
C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\1690823416.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_ajio[col] = df_ajio[col].fillna("unknown")

***Snpdeal Dataset- Data Wrangling***

In [230]:
#creating dataframes
df_snapdeal=pd.read_csv('snapdeal_women_shirts_full.csv')
print("Total number of rows in snapdeal_women_shirts_full.csv: ", len(df_snapdeal))

Total number of rows in snapdeal_women_shirts_full.csv:  1957

In [231]:
df_snapdeal.shape

(1957, 22)

In [232]:
df_snapdeal.head(2)

,website_name,product_name,product_image,brand,category,subcategory,price,original_price,discount_percent,rating,...,color,fit_type,fabric,sleeve_type,pattern,description,availability,seller,product_url,scrape_date
0,Snapdeal,OTIRA Women Solid Poly Crepe Shirt ( Black ),https://g.sdlcdn.com/imgs/k/1/r/OTIRA-Black-Po...,OTIRA,Women,Shirts,402,1475,73,4.4,...,Mint Green,Regular Fit,Poly Crepe,Full Sleeves,Solid,Fabric: Poly Crepe. Fit: Regular Fit. Sleeves ...,InStock,doek design private limited,https://www.snapdeal.com/product/otira-blue-po...,2026-06-29T05:30:39.158595+00:00
1,Snapdeal,Mahadev Fashion Women Cotton Blend Shirt ( Mul...,https://g.sdlcdn.com/imgs/l/d/7/Mahadev-Fashio...,Mahadev Fashion,Women,Shirts,448,999,55,5.0,...,Multi Color,Regular,Cotton Blend,3/4th Sleeves,NaN,Fabric: Cotton Blend. Fit: Regular. Sleeves Le...,InStock,mahadev fashion,https://www.snapdeal.com/product/mahadev-fashi...,2026-06-29T05:30:39.158595+00:00

In [233]:
df_snapdeal.isnull().sum()

website_name           0
product_name           0
product_image          0
brand                  1
category               0
subcategory            0
price                  0
original_price         0
discount_percent       0
rating                 0
review_count           0
size_options           5
color                  0
fit_type               1
fabric                 0
sleeve_type            1
pattern             1038
description            0
availability           0
seller                 0
product_url            0
scrape_date            0
dtype: int64

In [234]:
#transforming  the product name column
df_snapdeal['product_name']=df_snapdeal['product_name'].str.split('(').str[0]

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\1919073396.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snapdeal['product_name']=df_snapdeal['product_name'].str.split('(').str[0]

In [235]:
#filling the null values in the brand column
df_snapdeal['brand']=df_snapdeal['brand'].fillna("unknown")

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\3090539193.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snapdeal['brand']=df_snapdeal['brand'].fillna("unknown")

In [236]:
#filling null values for size_options column
df_snapdeal['size_options']=df_snapdeal['size_options'].fillna("unknown")

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\705221597.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snapdeal['size_options']=df_snapdeal['size_options'].fillna("unknown")

In [237]:
#filling the null values for fit column
df_snapdeal["fit_type"]=df_snapdeal["fit_type"].fillna("unknown")

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\2022383773.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snapdeal["fit_type"]=df_snapdeal["fit_type"].fillna("unknown")

In [238]:
#filling null values for SLVEES COLUMN
df_snapdeal["sleeve_type"]=df_snapdeal["sleeve_type"].fillna("unknown")

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\4293675450.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snapdeal["sleeve_type"]=df_snapdeal["sleeve_type"].fillna("unknown")

In [239]:
df_snapdeal["pattern"]=df_snapdeal["pattern"].fillna("unknown")

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\1765925070.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snapdeal["pattern"]=df_snapdeal["pattern"].fillna("unknown")

In [240]:
#transforming the column names in lower case
df_snapdeal.columns=df_snapdeal.columns.str.lower()

In [241]:
df_raw= pd.concat([df_ajio, df_amazon, df_flipkart, df_myntra, df_snapdeal],ignore_index=True)

In [242]:
df_raw.shape

(4190, 22)

In [243]:
before = len(df_raw)
df_raw = df_raw.drop_duplicates(subset='product_url', keep='first').reset_index(drop=True)
print("Removed:", before - len(df_raw), "| Remaining:", len(df_raw))

Removed: 0 | Remaining: 4190

In [244]:
df_raw.columns

Index(['website_name', 'product_name', 'product_image', 'brand', 'category',
       'subcategory', 'price', 'original_price', 'discount_percent', 'rating',
       'review_count', 'size_options', 'color', 'fit_type', 'fabric',
       'sleeve_type', 'pattern', 'description', 'availability', 'seller',
       'product_url', 'scrape_date'],
      dtype='object')

In [245]:
col=['website_name','product_name','brand','category','subcategory', 'color','fit_type','fabric',
       'sleeve_type', 'pattern', 'description', 'availability', 'seller' ]
for i in col:
    df_raw[i] = df_raw[i].str.strip().str.lower()

C:\Users\SAKSHI\AppData\Local\Temp\ipykernel_32396\1283784241.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_raw[i] = df_raw[i].str.strip().str.lower()

In [246]:
df_raw.to_excel('combined_women_shirts.xlsx', index=False)